# Generated by Django 3.2.9 on 2021-11-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='city',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='zip_code',
            new_name='postal_code',
        ),
    ]
