# Generated by Django 3.2.9 on 2021-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20211113_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Postal Code'),
        ),
    ]
