# Generated by Django 3.2.9 on 2021-11-17 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_auto_20211115_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('locality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Locality')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('has_profile', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
